"""
URL configuration for siprac project.
"""
from django.contrib import admin
from django.urls import path

from core.views import (
    BuscarImoveisAPIView,
    ComentarioCreateView,
    DashboardView,
    EncaminhamentoCreateView,
    FinalidadesAPIView,
    ImovelCreateView,
    ImovelDetailView,
    ImovelListView,
    ImovelMapaView,
    ImovelUpdateView,
    OSEditarCampoView,
    OSEncerramentoView,
    OSDetailView,
    OSListView,
    OSLiberarProcessoView,
    OSReabrirNaUnidadeView,
    OSUploadInscricoesView,
    OSVincularImovelView,
    OSVincularProcessoView,
    OSWizardCancelarView,
    OSWizardPasso2View,
    OSWizardPasso3View,
    OSWizardView,
    PreferenciaGerencialView,
    ProcessoDetailView,
    ProcessoSeiAPIView,
    ProducaoAlterarStatusView,
    ProducaoCreateView,
    ProducaoDetailView,
    ProducaoEditarCampoView,
    ProducaoListView,
    ProducaoVincularImovelView,
    ProximoIsicAPIView,
    RelatorioListView,
    RelatorioProducaoView,
    RelatorioTempoRegistroView,
    ProximoNumeroAPIView,
    SiatAtualizarInscricaoView,
    SiatCarregarArquivoView,
    SiatCoordenadasBlocoView,
    SiatStatusView,
    SiatStatusIndexView,
    SiatLimparImoveisView,
    SipracLoginView,
    SipracLogoutView,
    TiposDemandaAPIView,
    TrocarPerfilView,
)

urlpatterns = [
    path('', DashboardView.as_view(), name='dashboard'),
    path('login/', SipracLoginView.as_view(), name='login'),
    path('logout/', SipracLogoutView.as_view(), name='logout'),
    path('trocar-perfil/', TrocarPerfilView.as_view(), name='trocar_perfil'),
    path('os/nova/', OSWizardView.as_view(), name='os_nova'),
    path(
        'os/nova/cancelar/',
        OSWizardCancelarView.as_view(),
        name='os_wizard_cancelar',
    ),
    path('os/nova/passo2/', OSWizardPasso2View.as_view(), name='os_nova_passo2'),
    path('os/nova/passo3/', OSWizardPasso3View.as_view(), name='os_nova_passo3'),
    path(
        'os/nova/upload-inscricoes/',
        OSUploadInscricoesView.as_view(),
        name='os_upload_inscricoes',
    ),
    path('os/<int:pk>/encaminhar/', EncaminhamentoCreateView.as_view(), name='os_encaminhar'),
    path(
        'os/<int:pk>/reabrir-unidade/',
        OSReabrirNaUnidadeView.as_view(),
        name='os_reabrir_unidade',
    ),
    path('os/<int:pk>/producao/', ProducaoCreateView.as_view(), name='os_producao'),
    path('producoes/', ProducaoListView.as_view(), name='producao_list'),
    path('processos/<int:pk>/', ProcessoDetailView.as_view(), name='processo_detail'),
    path('producoes/<int:pk>/', ProducaoDetailView.as_view(), name='producao_detail'),
    path(
        'producoes/<int:pk>/status/',
        ProducaoAlterarStatusView.as_view(),
        name='producao_alterar_status',
    ),
    path(
        'producoes/<int:pk>/editar-campo/',
        ProducaoEditarCampoView.as_view(),
        name='producao_editar_campo',
    ),
    path(
        'producoes/<int:pk>/imoveis/',
        ProducaoVincularImovelView.as_view(),
        name='producao_vincular_imovel',
    ),
    path(
        'producoes/<int:prod_pk>/comentarios/',
        ComentarioCreateView.as_view(),
        name='producao_comentarios',
    ),
    path('os/<int:pk>/encerrar/', OSEncerramentoView.as_view(), name='os_encerrar'),
    path('os/<int:pk>/imoveis/vincular/', OSVincularImovelView.as_view(), name='os_vincular_imovel'),
    path(
        'os/<int:pk>/processos/vincular/',
        OSVincularProcessoView.as_view(),
        name='os_vincular_processo',
    ),
    path(
        'os/<int:os_pk>/processos/<int:proc_pk>/liberar/',
        OSLiberarProcessoView.as_view(),
        name='os_liberar_processo',
    ),
    path('os/<int:pk>/editar-campo/', OSEditarCampoView.as_view(), name='os_editar_campo'),
    path('os/<int:pk>/', OSDetailView.as_view(), name='os_detalhe'),
    path('os/<int:os_pk>/comentarios/', ComentarioCreateView.as_view(), name='os_comentarios'),
    path('os/', OSListView.as_view(), name='os_list'),
    path('imoveis/novo/', ImovelCreateView.as_view(), name='imovel_novo'),
    path('imoveis/mapa/', ImovelMapaView.as_view(), name='imovel_mapa'),
    path('imoveis/<int:pk>/editar/', ImovelUpdateView.as_view(), name='imovel_editar'),
    path('imoveis/<int:pk>/', ImovelDetailView.as_view(), name='imovel_detalhe'),
    path('imoveis/', ImovelListView.as_view(), name='imovel_list'),
    path('relatorios/', RelatorioListView.as_view(), name='relatorio_list'),
    path(
        'relatorios/producao/',
        RelatorioProducaoView.as_view(),
        name='relatorio_producao',
    ),
    path(
        'relatorios/tempo-registro/',
        RelatorioTempoRegistroView.as_view(),
        name='relatorio_tempo_registro',
    ),
    path('admin-siprac/carregar-siat/', SiatCarregarArquivoView.as_view(), name='siat_carregar'),
    path('admin-siprac/siat-status/', SiatStatusView.as_view(), name='siat_status'),
    path('admin-siprac/siat-limpar/', SiatLimparImoveisView.as_view(), name='siat_limpar'),
    path(
        'api/siat/status-indice/',
        SiatStatusIndexView.as_view(),
        name='api_siat_status_indice',
    ),
    path(
        'api/siat/atualizar-inscricao/<int:inscricao>/',
        SiatAtualizarInscricaoView.as_view(),
        name='api_siat_atualizar_inscricao',
    ),
    path(
        'api/siat/coordenadas-bloco/<str:num_bloco>/',
        SiatCoordenadasBlocoView.as_view(),
        name='api_siat_coordenadas_bloco',
    ),
    path('api/buscar-imoveis/', BuscarImoveisAPIView.as_view(), name='api_buscar_imoveis'),
    path('api/processo-sei/', ProcessoSeiAPIView.as_view(), name='api_processo_sei'),
    path('api/tipos-demanda/', TiposDemandaAPIView.as_view(), name='api_tipos_demanda'),
    path('api/finalidades/', FinalidadesAPIView.as_view(), name='api_finalidades'),
    path('api/proximo-numero/', ProximoNumeroAPIView.as_view(), name='api_proximo_numero'),
    path('api/proximo-isic/', ProximoIsicAPIView.as_view(), name='api_proximo_isic'),
    path('api/preferencias-gerencial/', PreferenciaGerencialView.as_view(), name='api_preferencias_gerencial'),
    path('admin/', admin.site.urls),
]
