# Generated by Django 6.0.5 on 2026-05-31 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Finalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('ativa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'finalidade',
                'verbose_name_plural': 'finalidades',
                'db_table': 'FINALIDADE',
            },
        ),
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_identificacao', models.CharField(max_length=255)),
                ('inscricao_cadastral', models.CharField(blank=True, max_length=255, null=True)),
                ('codigo_isic', models.CharField(blank=True, max_length=255, null=True)),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('bairro', models.CharField(blank=True, max_length=255, null=True)),
                ('area_referencia', models.FloatField(blank=True, null=True)),
                ('exercicio_referencia', models.IntegerField(blank=True, null=True)),
                ('origem_dados', models.CharField(blank=True, max_length=255, null=True)),
                ('editado_manualmente', models.BooleanField(default=False)),
                ('data_ultima_importacao', models.DateField(blank=True, null=True)),
                ('observacao_interna', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'imóvel',
                'verbose_name_plural': 'imóveis',
                'db_table': 'IMOVEL',
            },
        ),
        migrations.CreateModel(
            name='Natureza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('ativa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'natureza',
                'verbose_name_plural': 'naturezas',
                'db_table': 'NATUREZA',
            },
        ),
        migrations.CreateModel(
            name='PerfilAcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('pode_criar_os', models.BooleanField(default=False)),
                ('pode_encerrar_os', models.BooleanField(default=False)),
                ('pode_criar_os_interna', models.BooleanField(default=False)),
                ('pode_homologar', models.BooleanField(default=False)),
                ('visibilidade_total', models.BooleanField(default=False)),
                ('admin_sistema', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'perfil de acesso',
                'verbose_name_plural': 'perfis de acesso',
                'db_table': 'PERFIL_ACESSO',
            },
        ),
        migrations.CreateModel(
            name='ProcessoSei',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_processo', models.CharField(max_length=255)),
                ('data_abertura_sei', models.DateField(blank=True, null=True)),
                ('situacao', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'processo SEI',
                'verbose_name_plural': 'processos SEI',
                'db_table': 'PROCESSO_SEI',
            },
        ),
        migrations.CreateModel(
            name='Servidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('login', models.CharField(max_length=255, unique=True)),
                ('senha_hash', models.CharField(max_length=255)),
                ('salt', models.CharField(max_length=255)),
                ('data_ultimo_acesso', models.DateField(blank=True, null=True)),
                ('tentativas_falhas', models.IntegerField(default=0)),
                ('bloqueado', models.BooleanField(default=False)),
                ('token_reset_senha', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'servidor',
                'verbose_name_plural': 'servidores',
                'db_table': 'SERVIDOR',
            },
        ),
        migrations.CreateModel(
            name='TipoDemanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('ativa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'tipo de demanda',
                'verbose_name_plural': 'tipos de demanda',
                'db_table': 'TIPO_DEMANDA',
            },
        ),
        migrations.CreateModel(
            name='TipoProducao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefixo', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=255)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'tipo de produção',
                'verbose_name_plural': 'tipos de produção',
                'db_table': 'TIPO_PRODUCAO',
            },
        ),
        migrations.CreateModel(
            name='UnidadeExterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(blank=True, max_length=50, null=True)),
                ('nome', models.CharField(max_length=255)),
                ('espera_retorno_padrao', models.BooleanField(default=True)),
                ('ativa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'unidade externa',
                'verbose_name_plural': 'unidades externas',
                'db_table': 'UNIDADE_EXTERNA',
            },
        ),
        migrations.CreateModel(
            name='UnidadeInterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=50)),
                ('nome', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'unidade interna',
                'verbose_name_plural': 'unidades internas',
                'db_table': 'UNIDADE_INTERNA',
            },
        ),
        migrations.CreateModel(
            name='OS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_os', models.CharField(max_length=255, unique=True)),
                ('data_criacao_sgbd', models.DateField(auto_now_add=True)),
                ('data_entrada_divisao', models.DateField(blank=True, null=True)),
                ('os_interna', models.BooleanField(default=False)),
                ('pendente_confirmacao', models.BooleanField(default=False)),
                ('prioridade', models.CharField(default='NORMAL', max_length=255)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('finalidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordens_servico', to='core.finalidade')),
                ('natureza', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordens_servico', to='core.natureza')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordens_servico_criadas', to='core.servidor')),
                ('tipo_demanda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordens_servico', to='core.tipodemanda')),
            ],
            options={
                'verbose_name': 'ordem de serviço',
                'verbose_name_plural': 'ordens de serviço',
                'db_table': 'OS',
            },
        ),
        migrations.CreateModel(
            name='Producao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_producao', models.CharField(blank=True, max_length=255, null=True)),
                ('numero_sei', models.CharField(blank=True, max_length=255, null=True)),
                ('ano', models.IntegerField()),
                ('status', models.CharField(max_length=255)),
                ('data_homologacao', models.DateField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('os', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='producoes', to='core.os')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='producoes_criadas', to='core.servidor')),
                ('homologado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='producoes_homologadas', to='core.servidor')),
                ('tipo_producao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='producoes', to='core.tipoproducao')),
            ],
            options={
                'verbose_name': 'produção',
                'verbose_name_plural': 'produções',
                'db_table': 'PRODUCAO',
            },
        ),
        migrations.CreateModel(
            name='ProducaoAtributo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=255)),
                ('valor', models.CharField(max_length=255)),
                ('producao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atributos', to='core.producao')),
            ],
            options={
                'verbose_name': 'atributo de produção',
                'verbose_name_plural': 'atributos de produção',
                'db_table': 'PRODUCAO_ATRIBUTO',
            },
        ),
        migrations.CreateModel(
            name='ProducaoImovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo_ref', models.CharField(blank=True, max_length=255, null=True)),
                ('papel_no_grupo', models.CharField(blank=True, max_length=255, null=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='producoes', to='core.imovel')),
                ('producao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='imoveis', to='core.producao')),
            ],
            options={
                'verbose_name': 'imóvel na produção',
                'verbose_name_plural': 'imóveis na produção',
                'db_table': 'PRODUCAO_IMOVEL',
            },
        ),
        migrations.CreateModel(
            name='RegistroPesquisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_registro', models.CharField(max_length=255)),
                ('tipo_fonte', models.CharField(max_length=255)),
                ('data_registro', models.DateField()),
                ('data_encaminhamento', models.DateField(blank=True, null=True)),
                ('tipo_pesquisa', models.CharField(max_length=255)),
                ('semana_referencia', models.IntegerField(blank=True, null=True)),
                ('mes_referencia', models.IntegerField()),
                ('ano_referencia', models.IntegerField()),
                ('observacao', models.TextField(blank=True, null=True)),
                ('imovel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registros_pesquisa', to='core.imovel')),
                ('servidor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_pesquisa', to='core.servidor')),
            ],
            options={
                'verbose_name': 'registro de pesquisa',
                'verbose_name_plural': 'registros de pesquisa',
                'db_table': 'REGISTRO_PESQUISA',
            },
        ),
        migrations.CreateModel(
            name='PermissaoEspecial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_permissao', models.CharField(max_length=255)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('concedida_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='permissoes_concedidas', to='core.servidor')),
                ('servidor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='permissoes_especiais', to='core.servidor')),
            ],
            options={
                'verbose_name': 'permissão especial',
                'verbose_name_plural': 'permissões especiais',
                'db_table': 'PERMISSAO_ESPECIAL',
            },
        ),
        migrations.CreateModel(
            name='OsProcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_vinculo', models.CharField(max_length=255)),
                ('data_entrada_divisao', models.DateField(blank=True, null=True)),
                ('data_encerramento', models.DateField(blank=True, null=True)),
                ('motivo_encerramento', models.TextField(blank=True, null=True)),
                ('os', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processos_vinculados', to='core.os')),
                ('processo_sei', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vinculos_os', to='core.processosei')),
                ('encerrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='processos_encerrados', to='core.servidor')),
            ],
            options={
                'verbose_name': 'vínculo OS-processo SEI',
                'verbose_name_plural': 'vínculos OS-processo SEI',
                'db_table': 'OS_PROCESSO',
            },
        ),
        migrations.CreateModel(
            name='MacroetapaLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('macroetapa', models.CharField(max_length=255)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('automatico', models.BooleanField(default=False)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('os', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='macroetapas', to='core.os')),
                ('servidor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='macroetapas_registradas', to='core.servidor')),
            ],
            options={
                'verbose_name': 'registro de macroetapa',
                'verbose_name_plural': 'registros de macroetapa',
                'db_table': 'MACROETAPA_LOG',
                'ordering': ['-data_hora'],
            },
        ),
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidade', models.CharField(max_length=255)),
                ('entidade_id', models.IntegerField()),
                ('operacao', models.CharField(max_length=255)),
                ('campo_alterado', models.CharField(blank=True, max_length=255, null=True)),
                ('valor_anterior', models.TextField(blank=True, null=True)),
                ('valor_novo', models.TextField(blank=True, null=True)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('justificativa', models.TextField(blank=True, null=True)),
                ('servidor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='logs_auditoria', to='core.servidor')),
            ],
            options={
                'verbose_name': 'log de auditoria',
                'verbose_name_plural': 'logs de auditoria',
                'db_table': 'LOG_AUDITORIA',
                'ordering': ['-data_hora'],
            },
        ),
        migrations.CreateModel(
            name='Encaminhamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa_interna', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_acao', models.CharField(max_length=255)),
                ('aguarda_retorno', models.BooleanField(default=False)),
                ('data_retorno_prevista', models.DateField(blank=True, null=True)),
                ('data_retorno_efetiva', models.DateField(blank=True, null=True)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('os', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='encaminhamentos', to='core.os')),
                ('servidor_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='encaminhamentos_recebidos', to='core.servidor')),
                ('servidor_origem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='encaminhamentos_enviados', to='core.servidor')),
                ('unidade_externa_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='encaminhamentos', to='core.unidadeexterna')),
                ('unidade_interna_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='encaminhamentos_destino_interno', to='core.unidadeinterna')),
                ('unidade_interna_origem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='encaminhamentos_origem', to='core.unidadeinterna')),
            ],
            options={
                'verbose_name': 'encaminhamento',
                'verbose_name_plural': 'encaminhamentos',
                'db_table': 'ENCAMINHAMENTO',
                'ordering': ['-data_hora'],
            },
        ),
        migrations.CreateModel(
            name='TarefaInterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa_interna', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('data_inicio', models.DateTimeField()),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('encaminhamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tarefas', to='core.encaminhamento')),
                ('os', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tarefas_internas', to='core.os')),
                ('servidor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tarefas_internas', to='core.servidor')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tarefas_internas', to='core.unidadeinterna')),
            ],
            options={
                'verbose_name': 'tarefa interna',
                'verbose_name_plural': 'tarefas internas',
                'db_table': 'TAREFA_INTERNA',
            },
        ),
        migrations.CreateModel(
            name='ServidorUnidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=255)),
                ('substituto', models.BooleanField(default=False)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vinculos_servidor', to='core.perfilacesso')),
                ('servidor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vinculos_unidade', to='core.servidor')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vinculos_servidor', to='core.unidadeinterna')),
            ],
            options={
                'verbose_name': 'vínculo servidor-unidade',
                'verbose_name_plural': 'vínculos servidor-unidade',
                'db_table': 'SERVIDOR_UNIDADE',
            },
        ),
        migrations.CreateModel(
            name='MetaPesquisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_meta', models.CharField(max_length=255)),
                ('tipo_pesquisa', models.CharField(blank=True, max_length=255, null=True)),
                ('mes', models.IntegerField()),
                ('ano', models.IntegerField()),
                ('quantidade_meta', models.IntegerField()),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='metas_pesquisa_criadas', to='core.servidor')),
                ('servidor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='metas_pesquisa', to='core.servidor')),
                ('unidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='metas_pesquisa', to='core.unidadeinterna')),
            ],
            options={
                'verbose_name': 'meta de pesquisa',
                'verbose_name_plural': 'metas de pesquisa',
                'db_table': 'META_PESQUISA',
            },
        ),
        migrations.CreateModel(
            name='OsImovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vinculos_os', to='core.imovel')),
                ('os', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='imoveis_vinculados', to='core.os')),
            ],
            options={
                'verbose_name': 'vínculo OS-imóvel',
                'verbose_name_plural': 'vínculos OS-imóvel',
                'db_table': 'OS_IMOVEL',
                'constraints': [models.UniqueConstraint(fields=('os', 'imovel'), name='os_imovel_unico')],
            },
        ),
        migrations.CreateModel(
            name='ProducaoImovelDados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercicio', models.IntegerField()),
                ('area_trabalho', models.FloatField(blank=True, null=True)),
                ('endereco_trabalho', models.CharField(blank=True, max_length=255, null=True)),
                ('fonte', models.CharField(blank=True, max_length=255, null=True)),
                ('data_referencia', models.DateField()),
                ('observacao_tecnica', models.TextField(blank=True, null=True)),
                ('data_edicao', models.DateTimeField(blank=True, null=True)),
                ('producao_imovel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dados_trabalho', to='core.producaoimovel')),
                ('editado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dados_producao_editados', to='core.servidor')),
            ],
            options={
                'verbose_name': 'dados de trabalho do imóvel',
                'verbose_name_plural': 'dados de trabalho dos imóveis',
                'db_table': 'PRODUCAO_IMOVEL_DADOS',
                'constraints': [models.UniqueConstraint(fields=('producao_imovel', 'exercicio'), name='producao_imovel_exercicio_unico')],
            },
        ),
        migrations.CreateModel(
            name='CombinacaoValida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finalidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='combinacoes_validas', to='core.finalidade')),
                ('natureza', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='combinacoes_validas', to='core.natureza')),
                ('tipo_demanda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='combinacoes_validas', to='core.tipodemanda')),
            ],
            options={
                'verbose_name': 'combinação válida',
                'verbose_name_plural': 'combinações válidas',
                'db_table': 'COMBINACAO_VALIDA',
                'constraints': [models.UniqueConstraint(fields=('natureza', 'tipo_demanda', 'finalidade'), name='combinacao_valida_unica')],
            },
        ),
    ]
