# Generated by Django 6.0.5 on 2026-06-02 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_producao_data_criacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imovel',
            options={'verbose_name': 'Imóvel', 'verbose_name_plural': 'Imóveis'},
        ),
        migrations.RemoveField(
            model_name='imovel',
            name='area_referencia',
        ),
        migrations.RemoveField(
            model_name='imovel',
            name='endereco',
        ),
        migrations.AddField(
            model_name='imovel',
            name='area_construida',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='imovel',
            name='area_territorial',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='imovel',
            name='cod_logradouro',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imovel',
            name='coord_x',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='imovel',
            name='coord_y',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='imovel',
            name='des_finalidade',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='imovel',
            name='idf_regiao_homogenea',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imovel',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='imovel',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='imovel',
            name='nom_logradouro',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='imovel',
            name='num_bloco',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='imovel',
            name='num_endereco',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='imovel',
            name='num_unidade',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='imovel',
            name='num_versao',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='imovel',
            name='rh_nome',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='imovel',
            name='rh_valor',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='codigo_isic',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='inscricao_cadastral',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='origem_dados',
            field=models.CharField(choices=[('SIAT', 'SIAT'), ('MANUAL', 'Manual'), ('SIAT_EDITADO', 'SIAT Editado')], default='MANUAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='tipo_identificacao',
            field=models.CharField(choices=[('CADASTRAL', 'Cadastral'), ('ISIC', 'ISIC')], max_length=10),
        ),
        migrations.AlterModelTable(
            name='imovel',
            table='imovel',
        ),
    ]
