# Generated by Django 6.0.5 on 2026-06-02 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_producao_status_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='producao',
            name='autor_trabalho',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='producoes_autor', to='core.servidor', verbose_name='Autor do trabalho'),
        ),
        migrations.AddField(
            model_name='producao',
            name='servidor_responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='producoes_responsavel', to='core.servidor', verbose_name='Servidor responsável'),
        ),
        migrations.CreateModel(
            name='ProducaoStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_anterior', models.CharField(blank=True, max_length=20, null=True)),
                ('status_novo', models.CharField(max_length=20)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('justificativa', models.TextField(blank=True, null=True)),
                ('producao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_logs', to='core.producao')),
                ('servidor_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='status_logs_destino', to='core.servidor')),
                ('servidor_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='status_logs_origem', to='core.servidor')),
                ('unidade_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.unidadeinterna')),
            ],
            options={
                'verbose_name': 'Log de status da produção',
                'verbose_name_plural': 'Logs de status da produção',
                'db_table': 'producao_status_log',
                'ordering': ['data_hora'],
            },
        ),
        migrations.CreateModel(
            name='TipoProducaoUnidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_producao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unidades_competentes', to='core.tipoproducao')),
                ('unidade_interna', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tipos_producao', to='core.unidadeinterna')),
            ],
            options={
                'verbose_name': 'Competência por unidade',
                'verbose_name_plural': 'Competências por unidade',
                'db_table': 'tipo_producao_unidade',
                'constraints': [models.UniqueConstraint(fields=('tipo_producao', 'unidade_interna'), name='tipo_producao_unidade_unico')],
            },
        ),
    ]
