# Generated by Django 6.0.5 on 2026-06-09 02:36

import django.db.models.deletion
from django.db import migrations, models


def _origem_normalizada(valor):
    if valor in ("SIAT", "MANUAL"):
        return valor
    if valor == "SIAT_EDITADO":
        return "MANUAL"
    return "SIAT"


def _tem_dados_cadastrais_imovel(imovel):
    campos = (
        "nom_logradouro",
        "num_bloco",
        "bairro",
        "area_territorial",
        "exercicio_referencia",
    )
    return any(getattr(imovel, campo, None) for campo in campos)


def _criar_versao(imovel_versao_model, imovel, dados):
    exercicio = dados.get("exercicio")
    num_versao = dados.get("num_versao") or 0
    versao, criada = imovel_versao_model.objects.get_or_create(
        imovel=imovel,
        exercicio=exercicio,
        num_versao=num_versao,
        defaults={
            "num_bloco": dados.get("num_bloco"),
            "cod_logradouro": dados.get("cod_logradouro"),
            "nom_logradouro": dados.get("nom_logradouro"),
            "num_endereco": dados.get("num_endereco"),
            "num_unidade": dados.get("num_unidade"),
            "bairro": dados.get("bairro"),
            "des_finalidade": dados.get("des_finalidade"),
            "area_territorial": dados.get("area_territorial"),
            "area_construida": dados.get("area_construida"),
            "rh_nome": dados.get("rh_nome"),
            "rh_valor": dados.get("rh_valor"),
            "idf_regiao_homogenea": dados.get("idf_regiao_homogenea"),
            "latitude": dados.get("latitude"),
            "longitude": dados.get("longitude"),
            "coord_x": dados.get("coord_x"),
            "coord_y": dados.get("coord_y"),
            "origem_dados": _origem_normalizada(dados.get("origem_dados")),
        },
    )
    return versao, criada


def migrar_para_imovel_versao(apps, schema_editor):
    Imovel = apps.get_model("core", "Imovel")
    ImovelVersao = apps.get_model("core", "ImovelVersao")
    OsImovel = apps.get_model("core", "OsImovel")
    ProducaoImovel = apps.get_model("core", "ProducaoImovel")
    ProducaoImovelDados = apps.get_model("core", "ProducaoImovelDados")

    versoes_por_imovel = {}

    for imovel in Imovel.objects.all():
        if not _tem_dados_cadastrais_imovel(imovel):
            continue
        versao, _ = _criar_versao(
            ImovelVersao,
            imovel,
            {
                "exercicio": imovel.exercicio_referencia,
                "num_versao": imovel.num_versao,
                "num_bloco": imovel.num_bloco,
                "cod_logradouro": imovel.cod_logradouro,
                "nom_logradouro": imovel.nom_logradouro,
                "num_endereco": imovel.num_endereco,
                "num_unidade": imovel.num_unidade,
                "bairro": imovel.bairro,
                "des_finalidade": imovel.des_finalidade,
                "area_territorial": imovel.area_territorial,
                "area_construida": imovel.area_construida,
                "rh_nome": imovel.rh_nome,
                "rh_valor": imovel.rh_valor,
                "idf_regiao_homogenea": imovel.idf_regiao_homogenea,
                "latitude": imovel.latitude,
                "longitude": imovel.longitude,
                "coord_x": imovel.coord_x,
                "coord_y": imovel.coord_y,
                "origem_dados": imovel.origem_dados,
            },
        )
        versoes_por_imovel.setdefault(imovel.pk, []).append(versao)

    for os_imovel in OsImovel.objects.select_related("imovel").all():
        if os_imovel.snap_nom_logradouro or os_imovel.snap_inscricao_cadastral:
            versao, _ = _criar_versao(
                ImovelVersao,
                os_imovel.imovel,
                {
                    "exercicio": os_imovel.snap_exercicio_referencia,
                    "num_versao": os_imovel.snap_num_versao,
                    "num_bloco": os_imovel.snap_num_bloco,
                    "cod_logradouro": os_imovel.snap_cod_logradouro,
                    "nom_logradouro": os_imovel.snap_nom_logradouro,
                    "num_endereco": os_imovel.snap_num_endereco,
                    "num_unidade": os_imovel.snap_num_unidade,
                    "bairro": os_imovel.snap_bairro,
                    "des_finalidade": os_imovel.snap_des_finalidade,
                    "area_territorial": os_imovel.snap_area_territorial,
                    "area_construida": os_imovel.snap_area_construida,
                    "rh_nome": os_imovel.snap_rh_nome,
                    "rh_valor": os_imovel.snap_rh_valor,
                    "idf_regiao_homogenea": os_imovel.snap_idf_regiao_homogenea,
                    "latitude": os_imovel.snap_latitude,
                    "longitude": os_imovel.snap_longitude,
                    "coord_x": os_imovel.snap_coord_x,
                    "coord_y": os_imovel.snap_coord_y,
                    "origem_dados": os_imovel.snap_origem_dados,
                },
            )
            os_imovel.imovel_versao_id = versao.pk
            os_imovel.save(update_fields=["imovel_versao_id"])
            versoes_por_imovel.setdefault(os_imovel.imovel_id, []).append(versao)
            continue

        versoes = versoes_por_imovel.get(os_imovel.imovel_id, [])
        if versoes:
            os_imovel.imovel_versao_id = versoes[-1].pk
            os_imovel.save(update_fields=["imovel_versao_id"])

    for producao_imovel in ProducaoImovel.objects.select_related("imovel").all():
        if producao_imovel.snap_nom_logradouro or producao_imovel.snap_inscricao_cadastral:
            versao, _ = _criar_versao(
                ImovelVersao,
                producao_imovel.imovel,
                {
                    "exercicio": producao_imovel.snap_exercicio_referencia,
                    "num_versao": producao_imovel.snap_num_versao,
                    "num_bloco": producao_imovel.snap_num_bloco,
                    "cod_logradouro": producao_imovel.snap_cod_logradouro,
                    "nom_logradouro": producao_imovel.snap_nom_logradouro,
                    "num_endereco": producao_imovel.snap_num_endereco,
                    "num_unidade": producao_imovel.snap_num_unidade,
                    "bairro": producao_imovel.snap_bairro,
                    "des_finalidade": producao_imovel.snap_des_finalidade,
                    "area_territorial": producao_imovel.snap_area_territorial,
                    "area_construida": producao_imovel.snap_area_construida,
                    "rh_nome": producao_imovel.snap_rh_nome,
                    "rh_valor": producao_imovel.snap_rh_valor,
                    "idf_regiao_homogenea": producao_imovel.snap_idf_regiao_homogenea,
                    "latitude": producao_imovel.snap_latitude,
                    "longitude": producao_imovel.snap_longitude,
                    "coord_x": producao_imovel.snap_coord_x,
                    "coord_y": producao_imovel.snap_coord_y,
                    "origem_dados": producao_imovel.snap_origem_dados,
                },
            )
            producao_imovel.imovel_versao_id = versao.pk
            producao_imovel.save(update_fields=["imovel_versao_id"])
            versoes_por_imovel.setdefault(producao_imovel.imovel_id, []).append(versao)
            continue

        os_vinculo = (
            OsImovel.objects.filter(
                imovel_id=producao_imovel.imovel_id,
                imovel_versao__isnull=False,
            )
            .order_by("-data_vinculo")
            .first()
        )
        if os_vinculo and os_vinculo.imovel_versao_id:
            producao_imovel.imovel_versao_id = os_vinculo.imovel_versao_id
            producao_imovel.save(update_fields=["imovel_versao_id"])
            continue

        versoes = versoes_por_imovel.get(producao_imovel.imovel_id, [])
        if versoes:
            producao_imovel.imovel_versao_id = versoes[-1].pk
            producao_imovel.save(update_fields=["imovel_versao_id"])

    for dados in ProducaoImovelDados.objects.select_related("producao_imovel__imovel").all():
        imovel = dados.producao_imovel.imovel
        versao, _ = _criar_versao(
            ImovelVersao,
            imovel,
            {
                "exercicio": dados.exercicio,
                "num_versao": dados.num_versao,
                "num_bloco": dados.num_bloco,
                "cod_logradouro": dados.cod_logradouro,
                "nom_logradouro": dados.nom_logradouro,
                "num_endereco": dados.num_endereco,
                "num_unidade": dados.num_unidade,
                "bairro": dados.bairro,
                "des_finalidade": dados.des_finalidade,
                "area_territorial": dados.area_territorial,
                "area_construida": dados.area_construida,
                "rh_nome": dados.rh_nome,
                "rh_valor": dados.rh_valor,
                "idf_regiao_homogenea": dados.idf_regiao_homogenea,
                "latitude": dados.latitude,
                "longitude": dados.longitude,
                "coord_x": dados.coord_x,
                "coord_y": dados.coord_y,
                "origem_dados": dados.origem_dados,
            },
        )
        if not dados.producao_imovel.imovel_versao_id:
            dados.producao_imovel.imovel_versao_id = versao.pk
            dados.producao_imovel.save(update_fields=["imovel_versao_id"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_producao_autor_trabalho_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImovelVersao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("exercicio", models.IntegerField(blank=True, null=True)),
                ("num_versao", models.IntegerField(default=0)),
                ("data_registro", models.DateField(auto_now_add=True)),
                ("num_bloco", models.CharField(blank=True, max_length=12, null=True)),
                ("cod_logradouro", models.IntegerField(blank=True, null=True)),
                (
                    "nom_logradouro",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "num_endereco",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "num_unidade",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("bairro", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "des_finalidade",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "area_territorial",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "area_construida",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("rh_nome", models.CharField(blank=True, max_length=20, null=True)),
                ("rh_valor", models.IntegerField(blank=True, null=True)),
                ("idf_regiao_homogenea", models.IntegerField(blank=True, null=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=12, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=12, null=True
                    ),
                ),
                (
                    "coord_x",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=15, null=True
                    ),
                ),
                (
                    "coord_y",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=15, null=True
                    ),
                ),
                (
                    "origem_dados",
                    models.CharField(
                        choices=[("SIAT", "SIAT"), ("MANUAL", "Manual")],
                        default="SIAT",
                        max_length=20,
                    ),
                ),
                (
                    "imovel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="versoes",
                        to="core.imovel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Versão do imóvel",
                "verbose_name_plural": "Versões dos imóveis",
                "db_table": "imovel_versao",
                "unique_together": {("imovel", "exercicio", "num_versao")},
            },
        ),
        migrations.AddField(
            model_name="osimovel",
            name="imovel_versao",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="os_imoveis",
                to="core.imovelversao",
            ),
        ),
        migrations.AddField(
            model_name="producaoimovel",
            name="imovel_versao",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="producao_imoveis",
                to="core.imovelversao",
            ),
        ),
        migrations.RunPython(migrar_para_imovel_versao, migrations.RunPython.noop),
        migrations.RemoveConstraint(
            model_name="producaoimoveldados",
            name="producao_imovel_exercicio_unico",
        ),
        migrations.AlterModelOptions(
            name="osimovel",
            options={
                "verbose_name": "Imóvel da OS",
                "verbose_name_plural": "Imóveis da OS",
            },
        ),
        migrations.AlterModelOptions(
            name="producaoimovel",
            options={
                "verbose_name": "Imóvel da produção",
                "verbose_name_plural": "Imóveis da produção",
            },
        ),
        migrations.RemoveConstraint(
            model_name="osimovel",
            name="os_imovel_unico",
        ),
        migrations.AlterUniqueTogether(
            name="osimovel",
            unique_together={("os", "imovel")},
        ),
        migrations.AlterField(
            model_name="osimovel",
            name="imovel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="os_imoveis",
                to="core.imovel",
            ),
        ),
        migrations.AlterField(
            model_name="osimovel",
            name="os",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="os_imoveis",
                to="core.os",
            ),
        ),
        migrations.AlterField(
            model_name="osimovel",
            name="vinculado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="imoveis_vinculados_os",
                to="core.servidor",
            ),
        ),
        migrations.AlterField(
            model_name="producaoimovel",
            name="grupo_ref",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="producaoimovel",
            name="imovel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="producao_imoveis",
                to="core.imovel",
            ),
        ),
        migrations.AlterField(
            model_name="producaoimovel",
            name="papel_no_grupo",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="producaoimovel",
            name="producao",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="producao_imoveis",
                to="core.producao",
            ),
        ),
        migrations.AlterModelTable(
            name="osimovel",
            table="os_imovel",
        ),
        migrations.AlterModelTable(
            name="producaoimovel",
            table="producao_imovel",
        ),
        migrations.AddIndex(
            model_name="imovel",
            index=models.Index(
                fields=["inscricao_cadastral"], name="imovel_inscric_8e6396_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="imovel",
            index=models.Index(fields=["codigo_isic"], name="imovel_codigo__a1fb6d_idx"),
        ),
        migrations.AddIndex(
            model_name="imovelversao",
            index=models.Index(
                fields=["nom_logradouro"], name="imovel_vers_nom_log_29f7f2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="imovelversao",
            index=models.Index(fields=["bairro"], name="imovel_vers_bairro_fab804_idx"),
        ),
        migrations.AddIndex(
            model_name="imovelversao",
            index=models.Index(
                fields=["num_bloco"], name="imovel_vers_num_blo_c3dd08_idx"
            ),
        ),
        migrations.RemoveField(model_name="osimovel", name="snap_area_construida"),
        migrations.RemoveField(model_name="osimovel", name="snap_area_territorial"),
        migrations.RemoveField(model_name="osimovel", name="snap_bairro"),
        migrations.RemoveField(model_name="osimovel", name="snap_cod_logradouro"),
        migrations.RemoveField(model_name="osimovel", name="snap_codigo_isic"),
        migrations.RemoveField(model_name="osimovel", name="snap_coord_x"),
        migrations.RemoveField(model_name="osimovel", name="snap_coord_y"),
        migrations.RemoveField(model_name="osimovel", name="snap_data_importacao"),
        migrations.RemoveField(model_name="osimovel", name="snap_des_finalidade"),
        migrations.RemoveField(model_name="osimovel", name="snap_exercicio_referencia"),
        migrations.RemoveField(model_name="osimovel", name="snap_idf_regiao_homogenea"),
        migrations.RemoveField(model_name="osimovel", name="snap_inscricao_cadastral"),
        migrations.RemoveField(model_name="osimovel", name="snap_latitude"),
        migrations.RemoveField(model_name="osimovel", name="snap_longitude"),
        migrations.RemoveField(model_name="osimovel", name="snap_nom_logradouro"),
        migrations.RemoveField(model_name="osimovel", name="snap_num_bloco"),
        migrations.RemoveField(model_name="osimovel", name="snap_num_endereco"),
        migrations.RemoveField(model_name="osimovel", name="snap_num_unidade"),
        migrations.RemoveField(model_name="osimovel", name="snap_num_versao"),
        migrations.RemoveField(model_name="osimovel", name="snap_origem_dados"),
        migrations.RemoveField(model_name="osimovel", name="snap_rh_nome"),
        migrations.RemoveField(model_name="osimovel", name="snap_rh_valor"),
        migrations.RemoveField(model_name="producaoimovel", name="snap_area_construida"),
        migrations.RemoveField(model_name="producaoimovel", name="snap_area_territorial"),
        migrations.RemoveField(model_name="producaoimovel", name="snap_bairro"),
        migrations.RemoveField(model_name="producaoimovel", name="snap_cod_logradouro"),
        migrations.RemoveField(model_name="producaoimovel", name="snap_codigo_isic"),
        migrations.RemoveField(model_name="producaoimovel", name="snap_coord_x"),
        migrations.RemoveField(model_name="producaoimovel", name="snap_coord_y"),
        migrations.RemoveField(model_name="producaoimovel", name="snap_data_importacao"),
        migrations.RemoveField(model_name="producaoimovel", name="snap_des_finalidade"),
        migrations.RemoveField(
            model_name="producaoimovel", name="snap_exercicio_referencia"
        ),
        migrations.RemoveField(
            model_name="producaoimovel", name="snap_idf_regiao_homogenea"
        ),
        migrations.RemoveField(
            model_name="producaoimovel", name="snap_inscricao_cadastral"
        ),
        migrations.RemoveField(model_name="producaoimovel", name="snap_latitude"),
        migrations.RemoveField(model_name="producaoimovel", name="snap_longitude"),
        migrations.RemoveField(model_name="producaoimovel", name="snap_nom_logradouro"),
        migrations.RemoveField(model_name="producaoimovel", name="snap_num_bloco"),
        migrations.RemoveField(model_name="producaoimovel", name="snap_num_endereco"),
        migrations.RemoveField(model_name="producaoimovel", name="snap_num_unidade"),
        migrations.RemoveField(model_name="producaoimovel", name="snap_num_versao"),
        migrations.RemoveField(model_name="producaoimovel", name="snap_origem_dados"),
        migrations.RemoveField(model_name="producaoimovel", name="snap_rh_nome"),
        migrations.RemoveField(model_name="producaoimovel", name="snap_rh_valor"),
        migrations.RemoveField(model_name="imovel", name="area_construida"),
        migrations.RemoveField(model_name="imovel", name="area_territorial"),
        migrations.RemoveField(model_name="imovel", name="bairro"),
        migrations.RemoveField(model_name="imovel", name="cod_logradouro"),
        migrations.RemoveField(model_name="imovel", name="coord_x"),
        migrations.RemoveField(model_name="imovel", name="coord_y"),
        migrations.RemoveField(model_name="imovel", name="data_ultima_importacao"),
        migrations.RemoveField(model_name="imovel", name="des_finalidade"),
        migrations.RemoveField(model_name="imovel", name="editado_manualmente"),
        migrations.RemoveField(model_name="imovel", name="exercicio_referencia"),
        migrations.RemoveField(model_name="imovel", name="idf_regiao_homogenea"),
        migrations.RemoveField(model_name="imovel", name="latitude"),
        migrations.RemoveField(model_name="imovel", name="longitude"),
        migrations.RemoveField(model_name="imovel", name="nom_logradouro"),
        migrations.RemoveField(model_name="imovel", name="num_bloco"),
        migrations.RemoveField(model_name="imovel", name="num_endereco"),
        migrations.RemoveField(model_name="imovel", name="num_unidade"),
        migrations.RemoveField(model_name="imovel", name="num_versao"),
        migrations.RemoveField(model_name="imovel", name="origem_dados"),
        migrations.RemoveField(model_name="imovel", name="rh_nome"),
        migrations.RemoveField(model_name="imovel", name="rh_valor"),
        migrations.RemoveField(model_name="producaoimoveldados", name="editado_por"),
        migrations.RemoveField(
            model_name="producaoimoveldados", name="producao_imovel"
        ),
        migrations.DeleteModel(name="ProducaoImovelDados"),
    ]
