# Generated by Django 6.0.5 on 2026-06-10 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_simplify_os_imovel_cadastro'),
    ]

    operations = [
        migrations.AddField(
            model_name='os',
            name='prazo_data',
            field=models.DateField(blank=True, null=True, verbose_name='Data do prazo'),
        ),
        migrations.AddField(
            model_name='os',
            name='prazo_tipo',
            field=models.CharField(choices=[('SEM_PRIORIDADE', 'Sem prioridade'), ('PRIORIDADE_GS', 'Prioridade - GS'), ('PRIORIDADE_GP', 'Prioridade - GP'), ('PRIORIDADE_IDOSO', 'Prioridade - Idoso'), ('OUVIDORIA', 'Ouvidoria'), ('PRIORIDADE_PGM', 'Prioridade - PGM'), ('JUDICIAL_COM_PRAZO', 'Judicial com prazo'), ('PRAZO_LEGAL', 'Prazo legal'), ('PRAZO_CONTRATUAL', 'Prazo contratual')], default='SEM_PRIORIDADE', max_length=30),
        ),
        migrations.AddField(
            model_name='producao',
            name='mes_cronograma',
            field=models.DateField(blank=True, null=True, verbose_name='Mês do cronograma'),
        ),
        migrations.AddField(
            model_name='producao',
            name='prazo_interno',
            field=models.DateField(blank=True, null=True, verbose_name='Prazo interno'),
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem', models.CharField(choices=[('OS', 'OS'), ('PRODUCAO', 'Produção')], max_length=10)),
                ('texto', models.TextField()),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('os', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comentarios', to='core.os')),
                ('producao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comentarios', to='core.producao')),
                ('servidor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comentarios', to='core.servidor')),
            ],
            options={
                'verbose_name': 'Comentário',
                'verbose_name_plural': 'Comentários',
                'db_table': 'comentario',
                'ordering': ['-data_hora'],
            },
        ),
    ]
