# Generated by Django 6.0.5 on 2026-06-10 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_os_prazo_data_os_prazo_tipo_producao_mes_cronograma_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processosei',
            name='data_abertura_sei',
            field=models.DateField(blank=True, null=True, verbose_name='Data de criação no SEI'),
        ),
    ]
