# Generated by Django 6.0.5 on 2026-06-10 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_processosei_data_abertura_sei'),
    ]

    operations = [
        migrations.AlterField(
            model_name='os',
            name='data_criacao_sgbd',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de criação no SIPRAC'),
        ),
    ]
