# Generated by Django 6.0.5 on 2026-06-10 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_os_data_criacao_sgbd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processosei',
            name='situacao',
        ),
        migrations.AlterField(
            model_name='processosei',
            name='numero_processo',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
