# Generated by Django 6.0.5 on 2026-06-15 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_osprocesso_data_vinculo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='os',
            options={'ordering': ['-data_criacao_sgbd'], 'verbose_name': 'ordem de serviço', 'verbose_name_plural': 'ordens de serviço'},
        ),
        migrations.AlterModelOptions(
            name='tipodemanda',
            options={'verbose_name': 'Requerimento', 'verbose_name_plural': 'Requerimentos'},
        ),
        migrations.AddField(
            model_name='os',
            name='apelido',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Apelido'),
        ),
        migrations.AlterField(
            model_name='os',
            name='tipo_demanda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordens_servico', to='core.tipodemanda', verbose_name='Requerimento'),
        ),
    ]
