# Generated by Django 6.0.5 on 2026-06-15 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_os_options_alter_tipodemanda_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osimovel',
            name='cod_logradouro',
            field=models.IntegerField(blank=True, null=True, verbose_name='CTM'),
        ),
    ]
