# Generated by Django 6.0.5 on 2026-06-15 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_osimovel_cod_logradouro'),
    ]

    operations = [
        migrations.AddField(
            model_name='producao',
            name='modelo_sugerido',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Modelo sugerido'),
        ),
        migrations.AddField(
            model_name='producao',
            name='revisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='producoes_revisor', to='core.servidor', verbose_name='Revisor'),
        ),
    ]
