# Generated by Django 6.0.5 on 2026-06-16 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_producao_modelo_sugerido_producao_revisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='producao',
            name='data_entrega_ajustes',
            field=models.DateField(blank=True, null=True, verbose_name='Data de entrega dos ajustes'),
        ),
        migrations.AddField(
            model_name='producao',
            name='data_entrega_avaliacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de entrega da avaliação'),
        ),
        migrations.AddField(
            model_name='producao',
            name='data_entrega_revisao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de entrega da revisão'),
        ),
    ]
