# Generated by Django 6.0.5 on 2026-06-16 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_producao_data_entrega_ajustes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferenciaGerencial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colunas_visiveis', models.JSONField(default=list)),
                ('servidor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferencia_gerencial', to='core.servidor')),
            ],
            options={
                'verbose_name': 'preferência gerencial',
                'verbose_name_plural': 'preferências gerenciais',
                'db_table': 'preferencia_gerencial',
            },
        ),
    ]
