# Generated by Django 6.0.5 on 2026-07-05 02:56

from django.db import migrations, models


def migrar_tipo_acao_encaminhamento(apps, schema_editor):
    Encaminhamento = apps.get_model("core", "Encaminhamento")
    Encaminhamento.objects.filter(tipo_acao="ATRIBUICAO").update(tipo_acao="ENTRADA")
    Encaminhamento.objects.filter(tipo_acao="ENCAMINHAMENTO_EXTERNO").update(
        tipo_acao="EXTERNO"
    )


def reverter_tipo_acao_encaminhamento(apps, schema_editor):
    Encaminhamento = apps.get_model("core", "Encaminhamento")
    Encaminhamento.objects.filter(tipo_acao="ENTRADA").update(tipo_acao="ATRIBUICAO")
    Encaminhamento.objects.filter(tipo_acao="EXTERNO").update(
        tipo_acao="ENCAMINHAMENTO_EXTERNO"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_preferenciagerencial'),
    ]

    operations = [
        migrations.RunPython(
            migrar_tipo_acao_encaminhamento,
            reverter_tipo_acao_encaminhamento,
        ),
        migrations.AlterField(
            model_name='encaminhamento',
            name='tipo_acao',
            field=models.CharField(choices=[('ENTRADA', 'Entrada'), ('DEVOLUCAO', 'Devolução'), ('SOLICITACAO_AJUSTE', 'Solicitação de ajuste'), ('EXTERNO', 'Externo'), ('HOMOLOGACAO', 'Homologação'), ('CONCLUSAO', 'Conclusão')], max_length=255),
        ),
    ]
