# Generated by Django 6.0.5 on 2026-07-05 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_encaminhamento_tipo_acao'),
    ]

    operations = [
        migrations.AddField(
            model_name='osprocesso',
            name='aguardando_redistribuicao',
            field=models.BooleanField(default=False, verbose_name='Aguardando redistribuição'),
        ),
        migrations.AddField(
            model_name='osprocesso',
            name='observacao_bloqueio',
            field=models.TextField(blank=True, null=True, verbose_name='Observação do bloqueio'),
        ),
    ]
