# Generated by Django 6.0.5 on 2026-07-05 17:16

import django.db.models.deletion
from django.db import migrations, models


MAPEAMENTO_MACROETAPA = {
    "ATENDIMENTO_INTERNO": "ATENDIMENTO_INTERNO",
    "ATENDIMENTO_EXTERNO": "ATENDIMENTO_EXTERNO",
    "RETORNO_EXTERNO": "RETORNO_EXTERNO",
    "INCLUSAO_PROCESSO_RELACIONADO": "INCLUSAO_PROCESSO",
    "REABERTURA": "ENTRADA_DIVISAO",
}


def migrar_macroetapas_para_encaminhamentos(apps, schema_editor):
    OS = apps.get_model("core", "OS")
    MacroetapaLog = apps.get_model("core", "MacroetapaLog")
    Encaminhamento = apps.get_model("core", "Encaminhamento")

    for os in OS.objects.all():
        ultimo_encerrado = (
            MacroetapaLog.objects.filter(os=os, macroetapa="ENCERRADO")
            .order_by("-data_hora", "-id")
            .first()
        )
        if ultimo_encerrado:
            os.encerrada = True
            os.data_encerramento = ultimo_encerrado.data_hora
            os.save(update_fields=["encerrada", "data_encerramento"])

    for log in MacroetapaLog.objects.exclude(
        macroetapa__in=["ENTRADA_DIVISAO", "ENCERRADO"]
    ).order_by("data_hora", "id"):
        tipo_macroetapa = MAPEAMENTO_MACROETAPA.get(log.macroetapa, log.macroetapa)
        Encaminhamento.objects.create(
            os_id=log.os_id,
            unidade_interna_origem=None,
            servidor_origem_id=log.servidor_id,
            unidade_interna_destino=None,
            servidor_destino=None,
            etapa_interna="SISTEMA",
            tipo_acao="AUTOMATICO",
            tipo_macroetapa=tipo_macroetapa,
            data_hora=log.data_hora,
            aguarda_retorno=False,
            automatico=log.automatico,
            observacao=log.observacao or "",
        )


def reverter_migracao_macroetapas(apps, schema_editor):
    OS = apps.get_model("core", "OS")
    Encaminhamento = apps.get_model("core", "Encaminhamento")

    Encaminhamento.objects.filter(tipo_acao="AUTOMATICO").delete()
    OS.objects.update(encerrada=False, data_encerramento=None)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_osprocesso_aguardando_redistribuicao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='encaminhamento',
            name='automatico',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='encaminhamento',
            name='tipo_macroetapa',
            field=models.CharField(blank=True, choices=[('ENTRADA_DIVISAO', 'Entrada na Divisão'), ('ATENDIMENTO_INTERNO', 'Atendimento Interno'), ('ATENDIMENTO_EXTERNO', 'Atendimento Externo'), ('RETORNO_EXTERNO', 'Retorno Externo'), ('INCLUSAO_PROCESSO', 'Inclusão de Processo'), ('ENCERRAMENTO', 'Encerramento')], max_length=30, null=True, verbose_name='Tipo de macroetapa'),
        ),
        migrations.AddField(
            model_name='os',
            name='data_encerramento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de encerramento'),
        ),
        migrations.AddField(
            model_name='os',
            name='encerrada',
            field=models.BooleanField(default=False, verbose_name='Encerrada'),
        ),
        migrations.AlterField(
            model_name='encaminhamento',
            name='servidor_origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='encaminhamentos_enviados', to='core.servidor'),
        ),
        migrations.AlterField(
            model_name='encaminhamento',
            name='tipo_acao',
            field=models.CharField(choices=[('ENTRADA', 'Entrada'), ('DEVOLUCAO', 'Devolução'), ('SOLICITACAO_AJUSTE', 'Solicitação de ajuste'), ('EXTERNO', 'Externo'), ('HOMOLOGACAO', 'Homologação'), ('CONCLUSAO', 'Conclusão'), ('AUTOMATICO', 'Automático')], max_length=255),
        ),
        migrations.AlterField(
            model_name='encaminhamento',
            name='unidade_interna_origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='encaminhamentos_origem', to='core.unidadeinterna'),
        ),
        migrations.RunPython(
            migrar_macroetapas_para_encaminhamentos,
            reverter_migracao_macroetapas,
        ),
    ]
