# Generated by Django 6.0.5 on 2026-07-13 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_refatorar_macroetapa_encaminhamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='encaminhamento',
            name='manter_aberta_na_unidade',
            field=models.BooleanField(default=False, verbose_name='Manter aberta na unidade de origem'),
        ),
        migrations.AddField(
            model_name='producao',
            name='numero_ajustes',
            field=models.PositiveIntegerField(default=0, verbose_name='Nº de ajustes'),
        ),
        migrations.AddField(
            model_name='producao',
            name='numero_revisao',
            field=models.PositiveIntegerField(default=0, verbose_name='Nº de revisões'),
        ),
        migrations.AlterField(
            model_name='producao',
            name='status',
            field=models.CharField(choices=[('ENTRADA', 'Não distribuído'), ('DISTRIBUIDO', 'Distribuído'), ('PARA_REVISAO', 'Para revisão'), ('PARA_AJUSTES', 'Para ajustes'), ('HOMOLOGAR', 'Homologar'), ('HOMOLOGADO', 'Homologado'), ('ENVIADO', 'Enviado'), ('CANCELADO', 'Cancelado')], default='ENTRADA', max_length=20),
        ),
        migrations.CreateModel(
            name='OsUnidadeStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('CONCLUIDA', 'Concluída na unidade'), ('REABERTA', 'Reaberta'), ('SOMENTE_LEITURA', 'Somente leitura')], default='ABERTA', max_length=20, verbose_name='Status')),
                ('data_abertura', models.DateTimeField(auto_now_add=True)),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('manter_aberta', models.BooleanField(default=False, verbose_name='Manter aberta ao encaminhar')),
                ('observacao', models.TextField(blank=True, null=True)),
                ('aberta_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='os_abertas_unidade', to='core.servidor')),
                ('concluida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='os_concluidas_unidade', to='core.servidor')),
                ('os', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_unidades', to='core.os', verbose_name='OS')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_os', to='core.unidadeinterna', verbose_name='Unidade')),
            ],
            options={
                'verbose_name': 'Status da OS na unidade',
                'verbose_name_plural': 'Status das OSs nas unidades',
                'db_table': 'os_unidade_status',
                'unique_together': {('os', 'unidade')},
            },
        ),
    ]
