# Generated by Django 6.0.5 on 2026-07-14 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_remover_producao_data_homologacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='osprocesso',
            name='registrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='processos_registrados', to='core.servidor', verbose_name='Registrado por'),
        ),
        migrations.AddField(
            model_name='unidadeinterna',
            name='tipo',
            field=models.CharField(choices=[('ADMINISTRATIVA', 'Administrativa'), ('OPERACIONAL', 'Operacional')], default='OPERACIONAL', max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='encaminhamento',
            name='etapa_interna',
            field=models.CharField(blank=True, choices=[('ENTRADA', 'Entrada'), ('TRIAGEM', 'Triagem'), ('EM_ATENDIMENTO', 'Em atendimento'), ('DEVOLUCAO', 'Devolução'), ('SOLICITACAO_AJUSTE', 'Solicitação de ajuste'), ('HOMOLOGACAO', 'Homologação'), ('CONCLUIDA', 'Concluída')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='osprocesso',
            name='tipo_vinculo',
            field=models.CharField(choices=[('PRINCIPAL', 'Principal'), ('RELACIONADO', 'Relacionado')], max_length=20),
        ),
        migrations.AlterField(
            model_name='tarefainterna',
            name='etapa_interna',
            field=models.CharField(choices=[('ENTRADA', 'Entrada'), ('TRIAGEM', 'Triagem'), ('EM_ATENDIMENTO', 'Em atendimento'), ('DEVOLUCAO', 'Devolução'), ('SOLICITACAO_AJUSTE', 'Solicitação de ajuste'), ('HOMOLOGACAO', 'Homologação'), ('CONCLUIDA', 'Concluída')], max_length=20),
        ),
    ]
