# Generated by Django 6.0.5 on 2026-07-14 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_migrar_tipo_acao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encaminhamento',
            name='tipo_acao',
        ),
    ]
