# Generated by Django 6.0.5 on 2026-07-19 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_add_visibilidade_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='os',
            name='pendente_encaminhamento',
            field=models.BooleanField(default=False, verbose_name='Pendente de encaminhamento'),
        ),
    ]
