# Generated by Django 6.0.5 on 2026-07-20 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_add_pendente_encaminhamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='os',
            name='data_entrada_notificacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de entrada em notificação'),
        ),
        migrations.AddField(
            model_name='tipoproducao',
            name='numero_manual',
            field=models.BooleanField(default=True, verbose_name='Numeração manual (transição)'),
        ),
        migrations.AddField(
            model_name='tipoproducao',
            name='subtipo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Subtipo'),
        ),
        migrations.AddField(
            model_name='tipoproducao',
            name='tem_numeracao_sequencial',
            field=models.BooleanField(default=True, verbose_name='Tem numeração sequencial'),
        ),
        migrations.AlterField(
            model_name='encaminhamento',
            name='tipo_macroetapa',
            field=models.CharField(blank=True, choices=[('ENTRADA_DIVISAO', 'Entrada na Divisão'), ('ATENDIMENTO_INTERNO', 'Atendimento Interno'), ('ATENDIMENTO_EXTERNO', 'Atendimento Externo'), ('RETORNO_EXTERNO', 'Retorno Externo'), ('INCLUSAO_PROCESSO', 'Inclusão de Processo'), ('NOTIFICACAO', 'Notificação'), ('ENCERRAMENTO', 'Encerramento')], max_length=30, null=True, verbose_name='Tipo de macroetapa'),
        ),
    ]
