# Generated by Django 6.0.5 on 2026-07-20 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_popular_tipos_producao_unidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='producao',
            name='prazo_rev',
            field=models.DateField(blank=True, null=True, verbose_name='Prazo do revisor'),
        ),
    ]
