# Generated by Django 6.0.5 on 2026-07-21 13:47

from django.db import migrations, models
from django.db.models import F


def migrar_prazo_aval(apps, schema_editor):
    Producao = apps.get_model('core', 'Producao')
    Producao.objects.filter(
        prazo_interno__isnull=False,
        prazo_aval__isnull=True,
    ).update(prazo_aval=F('prazo_interno'))


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_add_prazo_rev'),
    ]

    operations = [
        migrations.AddField(
            model_name='producao',
            name='prazo_aval',
            field=models.DateField(blank=True, null=True, verbose_name='Prazo do avaliador'),
        ),
        migrations.RunPython(migrar_prazo_aval, migrations.RunPython.noop),
    ]
