# Generated by Django 6.0.5 on 2026-07-21 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_add_prazo_aval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producao',
            name='data_ajustes_ok',
        ),
        migrations.RemoveField(
            model_name='producao',
            name='data_entrega_ajustes',
        ),
        migrations.RemoveField(
            model_name='producao',
            name='data_entrega_avaliacao',
        ),
        migrations.RemoveField(
            model_name='producao',
            name='data_entrega_revisao',
        ),
        migrations.RemoveField(
            model_name='producao',
            name='prazo_aval',
        ),
        migrations.RemoveField(
            model_name='producao',
            name='revisor',
        ),
        migrations.RemoveField(
            model_name='producao',
            name='servidor_responsavel',
        ),
    ]
