# Generated by Django 6.0.5 on 2026-07-22 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_remove_campos_avaliacao_revisao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producao',
            name='autor_trabalho',
        ),
        migrations.RemoveField(
            model_name='producao',
            name='data_homologar',
        ),
        migrations.RemoveField(
            model_name='producao',
            name='homologado_por',
        ),
        migrations.RemoveField(
            model_name='producao',
            name='mes_cronograma',
        ),
        migrations.RemoveField(
            model_name='producao',
            name='modelo_sugerido',
        ),
        migrations.RemoveField(
            model_name='producao',
            name='numero_ajustes',
        ),
        migrations.RemoveField(
            model_name='producao',
            name='numero_revisao',
        ),
        migrations.RemoveField(
            model_name='producao',
            name='prazo_interno',
        ),
        migrations.RemoveField(
            model_name='producao',
            name='prazo_rev',
        ),
        migrations.AlterField(
            model_name='producao',
            name='status',
            field=models.CharField(choices=[('NAO_DISTRIBUIDO', 'Não distribuído'), ('DISTRIBUIDO', 'Distribuído'), ('REVISAR', 'Revisar'), ('REVISADO', 'Revisado'), ('VER_AJUSTES', 'Ver ajustes'), ('ENTREGA_AJUSTES', 'Entrega de ajustes'), ('AJUSTES_OK', 'Ajustes OK'), ('HOMOLOGAR', 'Homologar'), ('ENVIADO', 'Enviado'), ('CANCELADO', 'Cancelado')], default='ENVIADO', max_length=20),
        ),
    ]
