# Generated by Django 6.0.5 on 2026-07-22 21:54

from django.db import migrations, models


def popular_data_inicio_ciclo(apps, schema_editor):
    OsUnidadeStatus = apps.get_model("core", "OsUnidadeStatus")
    for status in OsUnidadeStatus.objects.filter(data_inicio_ciclo__isnull=True):
        status.data_inicio_ciclo = status.data_abertura
        status.save(update_fields=["data_inicio_ciclo"])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_simplifica_producao_registro_concluido'),
    ]

    operations = [
        migrations.AddField(
            model_name='osunidadestatus',
            name='data_inicio_ciclo',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Início do ciclo atual na unidade'),
        ),
        migrations.AddField(
            model_name='osunidadestatus',
            name='prazo_previsto',
            field=models.DateField(blank=True, null=True, verbose_name='Prazo de atendimento na unidade'),
        ),
        migrations.RunPython(popular_data_inicio_ciclo, migrations.RunPython.noop),
    ]
