# Generated by Django 6.0.5 on 2026-07-22 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_osunidadestatus_prazo_ciclo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilacesso',
            name='pode_criar_os',
        ),
        migrations.RemoveField(
            model_name='perfilacesso',
            name='pode_criar_os_interna',
        ),
        migrations.RemoveField(
            model_name='perfilacesso',
            name='pode_encerrar_os',
        ),
        migrations.RemoveField(
            model_name='perfilacesso',
            name='pode_homologar',
        ),
        migrations.RemoveField(
            model_name='perfilacesso',
            name='visibilidade_total',
        ),
        migrations.AlterField(
            model_name='perfilacesso',
            name='visibilidade',
            field=models.CharField(choices=[('UNIDADE', 'Apenas sua unidade'), ('DEPARTAMENTO', 'Todas as OSs (edição completa)'), ('TOTAL', 'Total (edição completa)')], default='UNIDADE', max_length=15, verbose_name='Visibilidade'),
        ),
    ]
