# Generated by Django 6.0.5 on 2026-07-24 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_remove_perfil_flags_acao'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessoUnidadeHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrada', models.DateField(verbose_name='Data de entrada na unidade')),
                ('data_saida', models.DateField(blank=True, null=True, verbose_name='Data de saída da unidade')),
                ('ativo', models.BooleanField(default=True, verbose_name='Entrada ativa nesta unidade')),
                ('processo_sei', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas_unidade', to='core.processosei', verbose_name='Processo SEI')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entradas_processo', to='core.unidadeinterna', verbose_name='Unidade')),
            ],
            options={
                'verbose_name': 'entrada de processo na unidade',
                'verbose_name_plural': 'entradas de processo na unidade',
                'db_table': 'processo_unidade_historico',
                'ordering': ['-data_entrada', 'unidade__sigla'],
            },
        ),
    ]
